#!/usr/bin/env perl

# Copyright 2014-2020 SUSE LLC
# SPDX-License-Identifier: GPL-2.0-or-later

use Mojo::Base -strict, -signatures;
use Mojo::IOLoop ();
use FindBin ();
use lib "$FindBin::RealBin/../lib";
use OpenQA::WorkerNg ();

my $worker = OpenQA::WorkerNg->new();

$worker->configure_signal_handlers();
$worker->run();

Mojo::IOLoop->start unless Mojo::IOLoop->is_running;

exit $worker->exit_status;
